### ISSUE TITLE
[TreeSelect] 官网 Demo 自定义选中项展示多选标签 close 按钮失效且控制台报错

### ISSUE THREAD

**Issue by fython** [Tencent/tdesign-vue#2601]
### tdesign-vue 版本

1.3.1 & 1.4.8

### 重现链接

https://tdesign.woa.com/vue/components/tree-select?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E4%B8%AD%E9%A1%B9%E5%B1%95%E7%A4%BA

### 重现步骤

<img width="892" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/3166782/96cea00c-3598-46ee-a8a6-32a13efbd5c5">

TDesign Vue 官网 Demo（1.4.8 版本）- TreeSelect - 自定义选中项展示

### 期望结果

点击关闭按钮后，选项正常移除

### 实际结果

点击关闭按钮不生效，控制台报错：

```
[Vue warn]: Error in v-on handler: "TypeError: Cannot destructure property 'trigger' of 'ct' as it is undefined."

found in

---> <TTag>
       <TInput>
         <TInputMapprops>
           <TTagInput>
             <Anonymous>
               <Anonymous>
                 <TPopup>
                   <TPopupMapprops>
                     <TSelectInput>
                       <TTreeSelect>
                         <TSpace>
                           <Demoexamplevaluedisplay> at ../src/tree-select/_example/valuedisplay.vue
                             <Anonymous> at ../src/tree-select/tree-select.md
                               <Page> at src/components/page.vue
                                 <App> at src/App.vue
                                   <Root>
nn @ index.edbc1676.js:5
kE @ index.edbc1676.js:12
LE @ index.edbc1676.js:12
a1 @ index.edbc1676.js:12
Ah @ index.edbc1676.js:12
n @ index.edbc1676.js:12
o._wrapper @ index.edbc1676.js:16
index.edbc1676.js:12 TypeError: Cannot destructure property 'trigger' of 'ct' as it is undefined.
    at d.tagChange (index.edbc1676.js:127:51606)
    at onClose (index.edbc1676.js:127:56071)
    at Object.onClose (valuedisplay.2225eba7.js:1:12771)
    at rn (index.edbc1676.js:68:42532)
    at d.handleClose (index.edbc1676.js:68:134733)
    at Ah (index.edbc1676.js:12:10014)
    at SVGSVGElement.n (index.edbc1676.js:12:13598)
    at o._wrapper (index.edbc1676.js:16:2771)
```

### 框架版本

Vue 2.6

### 浏览器版本

114.0.5735.198（正式版本） (x86_64)

### 系统版本

macOS 13.4.1

**Comment by xiaosansiji** [comment]
fixed in 1.5.1
