### ISSUE TITLE
[打包报错] 执行yarn build 源码进行编译不通过

### ISSUE THREAD

**Issue by mengyaqian** [Tencent/tdesign-vue#2673]
### tdesign-vue 版本

拉的最新版本，直接执行打包。会报错。

### 重现步骤

node版本：18.14.0
系统： window

直接执行yarn build,会报下面的错误：
![image](https://github.com/Tencent/tdesign-vue/assets/21994480/ab67f770-4737-41f5-892b-5230d2e067e8)

于是把package.json里的预编译的命令先删除：
`"prebuild": "rimraf es/* esm/* lib/* cjs/* dist/*",`
在次执行yarn build，会报以下错误：
![image](https://github.com/Tencent/tdesign-vue/assets/21994480/024fcff9-f871-4193-96ae-9969d65f7cde)

### 期望结果

能正常打包

### 实际结果

打包失败

### 框架版本

vue2

### 系统版本

window10

### Node版本

18.14.0

**Comment by xiaosansiji** [comment]
有执行 `git submodule` 的相关指令拉取子仓库么？
https://github.com/Tencent/tdesign-vue/blob/develop/DEVELOP_GUIDE.md#%E5%88%9D%E5%A7%8B%E5%8C%96%E5%AD%90%E4%BB%93%E5%BA%93

**Comment by mengyaqian** [comment]
>有的，运行没问题，就是打包有问题。

**Comment by mengyaqian** [comment]
> 有执行 `git submodule` 的相关指令拉取子仓库么？ https://github.com/Tencent/tdesign-vue/blob/develop/DEVELOP_GUIDE.md#%E5%88%9D%E5%A7%8B%E5%8C%96%E5%AD%90%E4%BB%93%E5%BA%93

有执行git submodule，运行没问题，打包有问题。猜测是window的问题，你是用window还是mac？

**Comment by uyarn** [comment]
是windows的兼容问题

**Comment by mengyaqian** [comment]
> 是windows的兼容问题

请问有什么解决方案吗？

**Comment by cyanbaby** [comment]
我手动将src/_common 替换为 子仓库之后
npm run build 报错如下:
`$ npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> tdesign-vue@1.6.3 prebuild
> rimraf es/* esm/* lib/* cjs/* dist/* --glob


> tdesign-vue@1.6.3 build
> cross-env NODE_ENV=production rollup -c script/rollup.config.js && npm run build:tsc


src/**/style/index.js → es/...
(!) Generated empty chunks
style/index, affix/style/index, alert/style/index, anchor/style/index, auto-complete/style/index, avatar/style/index, back-top/style/index, badge/style/index, breadcrumb/style/index, button/style/index, calendar/style/index, card/style/index, cascader/style/index, checkbox/style/index, collapse/style/index, color-picker/style/index, comment/style/index, date-picker/style/index, dialog/style/index, divider/style/index, drawer/style/index, dropdown/style/index, form/style/index, grid/style/index, guide/style/index, image/style/index, image-viewer/style/index, input/style/index, input-adornment/style/index, input-number/style/index, layout/style/index, link/style/index, list/style/index, loading/style/index, menu/style/index, message/style/index, notification/style/index, pagination/style/index, popconfirm/style/index, popup/style/index, progress/style/index, radio/style/index, range-input/style/index, rate/style/index, select/style/index, select-input/style/index, skeleton/style/index, slider/style/index, space/style/index, steps/style/index, sticky-tool/style/index, swiper/style/index, switch/style/index, table/style/index, tabs/style/index, tag/style/index, tag-input/style/index, textarea/style/index, time-picker/style/index, timeline/style/index, tooltip/style/index, transfer/style/index, tree/style/index, tree-select/style/index, upload/style/index, watermark/style/index, cascader/components/style/index, color-picker/panel/style/index, date-picker/base/style/index, date-picker/panel/style/index, image-viewer/base/style/index, table/hooks/style/index, time-picker/panel/style/index, transfer/components/style/index, tree/hooks/style/index, upload/themes/style/index, color-picker/panel/format/style/index
created es/ in 1.7s

src/**/*.ts, src/**/*.tsx, !src/**/demos, !src/**/*.d.ts, !src/**/__tests__, !src/index-lib.ts → es/...
[!] Error: Could not resolve './style/css.js' from src/affix/style/index.js
Error: Could not resolve './style/css.js' from src/affix/style/index.js
    at error (C:\Users\zhangg\projects\cucurbitbaby\zhongji_copy\frontend\front_code_analysis\tdesign-vue\node_modules\.store\rollup@2.79.1\node_modules\rollup\dist\shared\rollup.js:198:30)
    at ModuleLoader.handleResolveId (C:\Users\zhangg\projects\cucurbitbaby\zhongji_copy\frontend\front_code_analysis\tdesign-vue\node_modules\.store\rollup@2.79.1\node_modules\rollup\dist\shared\rollup.js:22287:24)
    at C:\Users\zhangg\projects\cucurbitbaby\zhongji_copy\frontend\front_code_analysis\tdesign-vue\node_modules\.store\rollup@2.79.1\node_modules\rollup\dist\shared\rollup.js:22250:26`
