### ISSUE TITLE
[input] @keyup.native 报错

### ISSUE THREAD

**Issue by ifAandBisC** [Tencent/tdesign-vue#2982]
TypeError: Cannot destructure property 'e' of 'undefined' as it is undefined.
    at VueComponent.onKeyup (index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/analyze/search-helper.vue?vue&type=script&lang=js&:220:7)
    at keyup (templateLoader.js??vue-loader-options!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/analyze/search-helper.vue?vue&type=template&id=2ae1f374&:293:32)
    at invokeWithErrorHandling (vue.runtime.esm.js:1636:26)
    at HTMLDivElement.invoker (vue.runtime.esm.js:1931:14)
    at original._wrapper (vue.runtime.esm.js:6012:25)

**Comment by uyarn** [comment]
https://codesandbox.io/p/sandbox/tdesign-vue-demo-forked-h383yx
