### ISSUE TITLE
测试覆盖提示 don't know how to turn this value into a node 测试全部失败

### ISSUE THREAD

**Issue by Microbai** [Tencent/tdesign-vue#377]
**Describe Framework**

tdesign-vue

**Describe Environment**
WSL2.0 Ubuntu 20.24 Node v16.13.2 

**Describe the bug**
`  

      ● Test suite failed to run

    /home/erich/tdesign-vue/src/index.ts: don't know how to turn this value into a node

      at valueToNode (node_modules/@babel/types/lib/converters/valueToNode.js:98:9)
      at Object.valueToNode (node_modules/@babel/types/lib/converters/valueToNode.js:92:58)
      at Object.exit (node_modules/istanbul-lib-instrument/src/visitor.js:700:36)
      at PluginPass.exit (node_modules/babel-plugin-istanbul/lib/index.js:158:38)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:177:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:109:8)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:103:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:77:19)

      Test Suites: 95 failed, 95 total
      Tests:       0 total
      Snapshots:   0 total
      Time:        119.999 s
      Ran all test suites.

`

**Additional context**
npm run test:coverage

测试全部失败，全部提示 /home/erich/tdesign-vue/src/index.ts: don't know how to turn this value into a node

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue/pull/379 是babel7.17.x的问题 已经锁回7.16了 麻烦重新rebase 一下develop 再提交 如果本地需要跑测试 需要rm lock文件并重新install一下
